import Head from "next/head";
import Image from "next/image";
import About from "../components/Landing Page/About";
import Chat from "../components/Landing Page/Chat";
import Find from "../components/Landing Page/Find";
import Getapp from "../components/Landing Page/Getapp";
import Header from "../components/Landing Page/Header";
import Profiles from "../components/Landing Page/Profiles";
import Question from "../components/Landing Page/Question";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Orion Meet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <Chat />
        <Question />
        <Find />
        <About />
        <Profiles />
        <Getapp />
      </main>

      <footer></footer>
    </div>
  );
}
