import React from "react";
import Hero from "../components/Landing Page/Hero";
import Header from "../components/Landing Page/Header";
import About from "../components/Landing Page/About";
import Chat from "../components/Landing Page/Chat";
import Find from "../components/Landing Page/Find";
import Getapp from "../components/Landing Page/Getapp";
import Profiles from "../components/Landing Page/Profiles";
import Question from "../components/Landing Page/Question";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <div id="root"></div>
        <link rel="icon" href="./public/orionLogo.svg" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <meta charset="utf-8" />
        <meta name="description" content="Generated by create next app" />
        <title>Orion Meet</title>
      </Head>

      <main>
        <Header />
        <Hero />
        <Chat />
        <Question />
        {/* <Find />
        <About />
        <Profiles />
        <Getapp /> */}
      </main>

      <footer></footer>
    </div>
  );
}
